### ISSUE TITLE
Namespace pollution

### ISSUE THREAD

**Issue by bellrise** [hulkiedo17/libconf#2]
This library looks promising, but I have a problem about namespace pollution with by the functions defined in the header. They all have very generic names like `create_file`, which could very well be a user-defined function. I'm proposing a change to prefix all the public symbols with something like `lc_` for "libconf".

Also, I forked the project to remove CMake from the dependency list :)

**Comment by bellrise** [comment]
Added a `namespace` branch on my fork with the proposed changes, what do you think?

**Comment by hulkiedo17** [comment]
yes it's a good idea to change the names of the functions to avoid problems, I'll take care of it in the near future.

**Comment by hulkiedo17** [comment]
why was it necessary to remove cmake from the project? I think it's a great build tool. In any case, update the documentation in the compile.md file

**Comment by hulkiedo17** [comment]
about your new branch, I looked and thought that it’s better not just to add prefixes, but to rethink the names in a new way, so I’ll deal with it myself one of these days, well, or you can help with this and I will make a pull request

**Comment by bellrise** [comment]
What do you mean by "rethink the names"? Is it a totally different  style or something else?

**Comment by bellrise** [comment]
Oh and I removed cmake from my branch just because I cant have it installed on my system :)

**Comment by hulkiedo17** [comment]
i mean rename function names, with prefixes, like: lc_create_config(), lc_delete_config(), etc. More understandable for users

**Comment by bellrise** [comment]
Apart from the new names, I have an issue with the documentation. The current format is okay, but I still would like having some comments in the header files to read, without the need to open GitHub to read the .md documentation. Another alternative would be using man pages, but that depends on which option you think is best.

**Comment by hulkiedo17** [comment]
in future i will add a comments into header
