### ISSUE TITLE
lc_create_config file location

### ISSUE THREAD

**Issue by bellrise** [hulkiedo17/libconf#3]
`lc_create_config` places the created file in the home directory, which is very unexpected. After reading the section about the function in library.md, it's still unclear to why this works this way.

I propose changing the functionality of this function to:

`lc_create_config(path)` will create a config file at `path`. If `path` is not a full path, start at the working directory. If such file already exists, don't create it, just return the path. If the file cannot be created or read, return `NULL`.

**Comment by hulkiedo17** [comment]
yeah it's good idea, i will try to make this functionality
