### ISSUE TITLE
Library redesign

### ISSUE THREAD

**Issue by bellrise** [hulkiedo17/libconf#4]
This library contains a major design flaw. All these functions operate on a file, not an in-memory representation of the configuration fields. This is a problem for performance reasons, because I/O is very slow compared to a linked list or a hash map (whichever memory structure can be used to represent the configuration fields).

The change would mean replacing the `char *file` based API with a faster and safer, state based API. For example:

* `char *lc_create_config(char *file)` could be replaced with `lc_config_t *lc_load_config(char *path)`, which would return a (possibly opaque) structure containing the loaded fields, or `NULL`, depending if the function succeeds. The user then could read and write to this structure using other API functions. After finishing, a `lc_dump_config` or `lc_write_config` function could be called to write the data contained in the structure back into the file system.
* `void lc_free_config(lc_config_t *config)` would free the created structure.

The safety from this approach would come from using the in-memory data structure, which can be loaded and written only once, before and after any modifications. This would mean that the library doesn't have to depend on some other program or even user changing the config file mid-processing, which could possibly break the parsing system or just load invalid data.

This may be a totally different goal which you had over this library, but if you decide to migrate I'll be glad to help.

**Comment by hulkiedo17** [comment]
Yes, this is a good decision. At first I thought that it would be normal to read from the file right away, but then I thought that it might be a little slower than reading it once, I already had experience with this. Thank you for your comment!
